# Generated by Django 4.1.5 on 2023-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('age', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=50)),
                ('gender', models.IntegerField(max_length=10)),
            ],
        ),
    ]
