# Generated by Django 4.1.5 on 2023-02-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
